# Generated by Django 4.2.13 on 2026-06-13 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='converted_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='expense',
            name='currency',
            field=models.CharField(default='INR', max_length=3),
        ),
        migrations.AddField(
            model_name='expense',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=4, default=1.0, max_digits=10),
        ),
    ]
