# Generated by Django 4.2.13 on 2026-06-14 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('total_rows', models.IntegerField(default=0)),
                ('invalid_rows', models.IntegerField(default=0)),
                ('review_rows', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.group')),
            ],
        ),
        migrations.CreateModel(
            name='StagedExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField()),
                ('raw_data', models.JSONField(default=dict)),
                ('parsed_data', models.JSONField(default=dict)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('severity', models.CharField(default='none', max_length=50)),
                ('issue_codes', models.JSONField(default=list)),
                ('import_as', models.CharField(default='expense', max_length=50)),
                ('action_taken', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staged_rows', to='importer.importbatch')),
            ],
        ),
    ]
