# Generated by Django 4.2.13 on 2026-06-14 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagedexpense',
            name='messages',
            field=models.JSONField(default=list),
        ),
    ]
